package.json
yarn.lock

yarn add vue-select

---

src/components/DataTable/compenents/el-data-table/el-data-table.vue
src/components/DataZTree/components/ZTree/index.vue
src/components/ListTable/TableAction.vue
src/components/ListTable/index.vue
src/components/TagSearch/index.vue
src/views/assets/AssetList.vue

[update]修改搜索组件

---

src/i18n/langs/cn.js
src/i18n/langs/en.js
src/router/index.js
src/views/sessions/CommandStorageCreate.vue
src/views/sessions/ReplyStorageCreate.vue
src/views/sessions/Storage.vue

create reply storage

---

src/userviews/assets/index.vue

https://github.com/jumpserver/lina/issues/118

fix: 修复资产 Dialog Title显示错误问题

---

src/views/assets/Platform/PlatformCreateUpdate.vue

Closes https://github.com/jumpserver/jumpserver/issues/4207

feat: 添加平台编码选项

---

src/views/users/User/UserCreateUpdate.vue
src/views/users/User/UserDetail/UserInfo.vue

Closes https://github.com/jumpserver/trello/issues/44

fix: 用户来源不为Local的时候禁止更新密码

---

src/views/users/User/UserList.vue

Closes https://github.com/jumpserver/trello/issues/29

fix(Userlist): 添加禁止更新和禁止删除的权限判断

---

src/components/AssetUserTable/index.vue

Closes https://github.com/jumpserver/trello/issues/30

fix(AssetUserTable): 去掉删除资产的前端提示，改为由后端提示

---

src/userviews/users/UserProfile/PasswordUpdate.vue

Closes https://github.com/jumpserver/trello/issues/23

fix(UserProfile): 修复登录密码后没有立即提示退出登录等问题

---

src/i18n/langs/cn.json
src/i18n/langs/en.json
src/views/sessions/SessionDetail/SessionCommandList.vue
src/views/sessions/SessionDetail/SessionDetailCard.vue

Closes https://github.com/jumpserver/trello/issues/72

fix(SessionList): 修复命令详情参数及在线会话快捷操作组件

---

src/userviews/assets/index.vue

Closes https://github.com/jumpserver/trello/issues/75

fix: 更新Xpack代码&&用户界面资产添加备注选项

---

.github/workflows/jms-generic-action-handler.yml

ci(github): 添加通用action

---

src/layout/components/GenericCreateUpdatePage/index.vue

fix: 添加form组件的refs

---

src/components/DataTable/compenents/el-data-table/el-data-table.vue

Closes https://github.com/jumpserver/trello/issues/69
Closes https://github.com/jumpserver/trello/issues/68

fix(el-data-table): 修复翻页搜索结果不正确的问题

---

src/views/perms/AssetPermission/AssetPermissionList.vue
src/views/perms/DatabaseAppPermission/DatabaseAppPermissionList.vue
src/views/perms/RemoteAppPermission/RemoteAppPermissionList.vue

* fix(perms): 优化授权列表添加刷新按钮
* fix(perms): 优化授权列表添加导入导出按钮
Co-authored-by: jym503558564 <503558564@qq.com>

fix(perms): 优化授权列表添加刷新按钮 (#245)

---

src/components/ListTable/TableAction/ExportDialog.vue

Closes https://github.com/jumpserver/trello/issues/74

fix(dialog): 修复当有搜索条件时禁用导出所有选项

---

src/utils/common.js

Closes https://github.com/jumpserver/trello/issues/237

fix: 修复Safari时间显示问题

---

src/views/tickets/components/Comments.vue

Revert "pref(ticket): 优化工单评论显示，我的回复显示在右边，其它回复均显示在左边"

---

src/components/AssetRelationCard/index.vue
src/components/AssetSelect/index.vue
src/components/DataTable/compenents/el-data-table/el-data-table.vue
src/components/DataZTree/components/ZTree/index.vue
src/components/DatetimeRangePicker/index.vue
src/layout/components/NavHeader/Tickets.vue
src/layout/components/Page/LicenseExpireTip.vue
src/layout/components/Page/PageHeading.vue
src/utils/common.js
src/views/assets/Asset/AssetList.vue
src/views/audits/CommandExecutionList.vue
src/views/audits/FTPLogList.vue
src/views/audits/LoginLogList.vue
src/views/audits/OperateLogList.vue
src/views/audits/PasswordChangeLogList.vue
src/views/perms/AssetPermission/AssetPermissionDetail/AssetPermissionAsset.vue
src/views/sessions/CommandList.vue
src/views/sessions/SessionList/BaseList.vue
src/views/settings/License.vue
src/views/users/User/components/InviteUsersDialog.vue
src/views/xpack/ChangeAuthPlan/ChangeAuthPlanCreateUpdate.vue
src/views/xpack/Org/OrganizationDetail/OrganizationMembershipList.vue

* perf(permSelectAssetCard): 优化授权详情页中的添加资产，将已添加的资产disable掉
Co-authored-by: jym503558564 <503558564@qq.com>

chore: merge dev to master

---

src/views/dashboard/ResourceSummary.vue
src/views/sessions/SessionList/index.vue

Closes https://github.com/jumpserver/jumpserver/issues/5850

fix: 修复首页面板链接跳转有误的问题

---

src/i18n/langs/cn.json
src/i18n/langs/en.json
src/userviews/users/UserProfile/ProfileInfo.vue
src/views/settings/FeiShu.vue
src/views/settings/index.vue

* feat: 添加飞书
* s
* 翻译
* 翻译
Co-authored-by: xinwen <coderWen@126.com>

v2.13.0 rc1

---

package.json
yarn.lock

Revert "chore(deps): bump axios from 0.21.1 to 0.21.2"

---

src/i18n/langs/cn.json
src/i18n/langs/en.json
src/layout/components/NavHeader/Help.vue
src/views/settings/Other.vue

feat: 支持管理员配置导航栏上帮助中的url

---

src/i18n/langs/cn.json
src/i18n/langs/en.json
src/views/xpack/Cloud/Account/AccountList.vue
src/views/xpack/Cloud/const.js

feat: 云管同步支持OpenStack私有云同步

---

src/i18n/langs/cn.json
src/i18n/langs/en.json
src/views/applications/DatabaseApp/DatabaseAppList.vue
src/views/assets/SystemUser/SystemUserCreateUpdate/CommonUser/index.vue
src/views/assets/SystemUser/SystemUserList/CommonUserList.vue
src/views/perms/const.js

feat: 支持 MongoDB 数据库的纳管

---

src/components/AccountListTable/index.vue
vue.config.js

Revert "fix: 修改资产账号更新回调方法"

---

src/views/accounts/AccountBackupPlan/AccountBackupPlanDetail/index.vue
src/views/accounts/ChangeAuthPlan/index.vue
src/views/assets/Asset/AssetDetail/index.vue
src/views/assets/CommandFilter/CommandFilterDetail/index.vue
src/views/assets/Domain/DomainDetail/index.vue
src/views/assets/SystemUser/SystemUserList/index.vue
src/views/ops/TaskDetail/index.vue
src/views/perms/ApplicationPermission/ApplicationPermissionDetail/index.vue
src/views/perms/AssetPermission/AssetPermissionDetail/index.vue
src/views/settings/Terminal/index.vue
src/views/users/Group/UserGroupDetail/index.vue
src/views/users/Role/RoleDetail/index.vue
src/views/users/User/UserDetail/index.vue

* perf: debug account
* Debug: 添加 debug
* debug: 添加线上debug
* debug: remove vue config
* chore: diglog 添加vif
* debug: authbook
* chore: debug account
* fix: 修改资产账号更新弹窗组件传参方式
* perf: 修改 authbook
* fix: 修复资产账号的更新组件不生效问题
* perf: change build scropt
* feat: 配置概况页的路由权限
* fix: 修复工单流自定义用户获取全局用户bug
* feat: 用户详情tab页rbac控制
* feat: 用户组详情tab添加rbac
* feat: 资产详情tab添加rbac
* feat: 角色列表详情tab添加rbac
* feat: 资产管理详情页tab添加rbac
* feat: 账号管理详情tab增加rbac
* feat: 权限管理详情tab添加rbac
* feat: 作业中心详情tab添加rbac
* feat: 系统设置tab添加rbac
Co-authored-by: ibuler <ibuler@qq.com>
Co-authored-by: “怀磊” <2280131253@qq.com>
Co-authored-by: feng626 <1304903146@qq.com>

feat: 用户详情tab页rbac控制 (#1359)

---

src/i18n/langs/cn.json
src/i18n/langs/en.json
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/const.js

feat: 支持纳管百度云资产

---

src/layout/empty.js
src/layout/empty.vue
src/router/audit/index.js
src/router/audit/sessions.js
src/router/console/accounts.js
src/router/console/acls.js
src/router/console/applications.js
src/router/console/assets.js
src/router/console/index.js
src/router/console/ops.js
src/router/console/perms.js
src/router/console/sessions.js
src/router/console/users.js
src/router/console/xpack.js
src/router/settings/index.js
src/router/tickets/index.js
src/router/workspace/index.js
src/store/modules/permission.js

Revert "perf:: 修复empty组件为函数式组件"

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/const.js

feat: 云同步支持京东云

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/layout/components/NavHeader/AccountDropdown.vue
src/router/profile/index.js
src/views/profile/TempPassword.vue

feat: 支持临时密码 (one-time-password) 登录

feat: 支持临时密码 (one-time-password) 登录

---

src/components/AccountListTable/ShowSecretInfo.vue
src/components/AppAccountListTable/ShowSecretInfo.vue

perf: 查看账号管理中的密码记录日志

---

src/components/AccountListTable/index.vue
src/views/accounts/AssetAccount/AssetAccountList.vue
src/views/assets/Asset/AssetDetail/Account.vue

feat: 账号管理下的资产账号及系统用户下的资产账号支持批量删除

feat: 账号管理下的资产账号及系统用户下的资产账号支持批量删除

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json

文件上传的时候 会让人误以为是直接点击上传按钮。其实是两种方式：要么退拽到此处，或者点击此处上传文件。

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/settings/Terminal/Storage/CommandStorageCreateUpdate.vue

perf: 命令存储ES可根据日期动态建立索引

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/const.js

feat: 云同步资产支持Fusion Compute私有云

feat: 云同步资产支持Fusion Compute私有云

---

src/utils/jms.js

fix: 修复普通用户登录默认 404

---

src/views/applications/const.js

feat: 改密计划支持MongoDB改密

---

src/views/applications/DatabaseApp/DatabaseAppCreateUpdate.vue
src/views/applications/DatabaseApp/const.js

feat: MongoDB支持连接SSL类型

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/const.js

feat: 云同步支持资产同步腾讯云(轻量应用服务器)

---

src/views/applications/DatabaseApp/const.js

feat: feat: 支持连接开启了ssl的Redis数据库

feat: feat: 支持连接开启了ssl的Redis数据库

---

src/views/settings/Auth/OAuth2.vue

feat: 支持OAuth2协议自定义注销功能

---

src/layout/components/GenericCreateUpdateForm/index.vue
src/layout/components/GenericUpdateFormDialog/index.vue

Revert "fix: form表单组件增加是否回显配置；批量更新弹窗组件默认设置为不回显"

---

src/views/settings/SMS/Base.vue
src/views/settings/SMS/CMPP2.vue
src/views/settings/SMS/SMSAlibaba.vue
src/views/settings/SMS/SMSHuawei.vue
src/views/settings/SMS/SMSTencent.vue

perf: 优化短信配置错误提示不友好问题

---

Dockerfile

fix: 修正 Dockerfile

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/const.js

feat: 云同步支持金山云

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/applications/const.js
src/views/assets/SystemUser/SystemUserCreateUpdate/CommonUser/index.vue

feat: 支持纳管 clickhouse[Web Terminal]

feat: 支持纳管 clickhouse[Web Terminal]

---

src/components/TableFormatters/TwoTabFormatter.vue
src/components/TableFormatters/index.js
src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/audits/OperateLogList.vue

feat: 重构操作日志
操作日志界面显示变更信息
支持操作日志保存至ES

feat: 重构操作日志

---

src/views/accounts/AccountBackupPlan/AccountBackupPlanList.vue
src/views/accounts/ChangeAuthPlan/AppChangeAuthPlan/AppChangeAuthPlanList.vue
src/views/accounts/ChangeAuthPlan/AssetChangeAuthPlan/ChangeAuthPlanList.vue
src/views/acl/AssetAcl/AssetAclList.vue
src/views/assets/CommandFilter/CommandFilterList.vue
src/views/assets/Domain/DomainList.vue
src/views/assets/Label/LabelList.vue

feat: 显示部分资源的批量删除操作按钮
网域、资产标签、命令过滤、账号备份、改密计划、资产登录复核批量删除

feat: 显示部分资源的批量删除操作按钮

---

src/components/TableFormatters/TwoTabFormatter.vue
src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskCreateUpdate.vue

feat: 云资产同步支持选择IP类型

---

src/App.vue
src/store/modules/common.js
src/utils/org.js
src/views/accounts/ChangeAuthPlan/AppChangeAuthPlan/ChangeAuthPlanDetail/ChangeAuthPlanApp/index.vue
src/views/accounts/ChangeAuthPlan/AssetChangeAuthPlan/ChangeAuthPlanDetail/ChangeAuthPlanAsset/index.vue
src/views/perms/AssetPermission/AssetPermissionDetail/AssetPermissionAsset.vue
src/views/sessions/SessionDetail/SessionDetailInfo.vue
src/views/settings/Interface.vue
src/views/settings/License.vue
src/views/tickets/RequestApplicationPerm/Detail/TicketDetail.vue
src/views/tickets/RequestAssetPerm/Detail/TicketDetail.vue
src/views/tickets/TicketFlow/Detail/TicketDetail.vue
src/views/tickets/components/Comments.vue

Revert "perf: 优化刷新页面方法，避免刷新时页面出现空白"

---

src/components/TableFormatters/TwoTabFormatter.vue
src/utils/theme/index.js
src/views/audits/OperateLogList.vue

perf: 优化操作日志界面显示随主题变化
fix: 修复用户快速查看日志详情时，日志不正常显示问题

perf: 优化操作日志界面显示随主题变化

---

src/i18n/langs/ja.json
src/i18n/langs/zh.json

perf: 翻译用户的[邮件]改为[邮箱]"

---

src/views/applications/const.js

fix: 隐藏clickhouse改密入口

---

src/views/applications/const.js

fix: 去掉clickhouse改密入口

---

src/views/assets/CommandFilter/CommandFilterCreateUpdate.vue
src/views/assets/CommandFilter/CommandFilterDetail/Detail.vue

fix: 解决命令过滤获取不到一些应用的系统用户问题

---

src/layout/components/NavHeader/Organization.vue

Revert "feat: 切换组织选择器宽度自适应"

---

src/layout/components/NavLeft/index.vue
src/router/audit/index.js
src/router/index.js
src/router/workbench/index.js

Revert "feat: 仪表盘、工作台默认展开子菜单"

---

src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskCreateUpdate.vue
src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskDetail/detail.vue

feat: 优化云资产同步

---

src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskCreateUpdate.vue

perf: 优化云资产同步

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/accounts/AssetAccount/AssetAccountDetail/index.vue
src/views/assets/Asset/AssetDetail/index.vue
src/views/users/User/UserDetail/Activity.vue
src/views/users/User/UserDetail/index.vue

feat: 支持资源用户在详情页查看活动(Activities)时间线

feat: 支持资源用户在详情页查看活动(Activities)时间线

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Asset/AssetCreateUpdate/DatabaseCreateUpdate.vue
src/views/assets/Asset/AssetDetail/index.vue
src/views/assets/Asset/AssetList/components/BaseList.vue
src/views/assets/Asset/AssetList/components/PlatformDialog.vue

feat: Redis/MongoDB 支持SSL

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/accounts/AssetAccount/AssetAccountDetail/Activity.vue
src/views/assets/Asset/AssetDetail/components/Activity.vue
src/views/users/User/UserDetail/Activity.vue

perf: 优化activity记录都保存至operatelog中

perf: 优化activity记录都保存至operatelog中

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/audits/OperateLogList.vue
src/views/audits/components/OperateLogDetail.vue

perf: 优化操作日志详情

---

src/views/assets/Asset/AssetCreateUpdate/DatabaseCreateUpdate.vue
src/views/assets/Asset/AssetDetail/index.vue
src/views/assets/Asset/AssetList/components/BaseList.vue
src/views/assets/Asset/AssetList/components/PlatformDialog.vue

fix: 自定义平台(Redis/MongoDB)无ssl选项

fix: 自定义平台(Redis/MongoDB)无ssl选项

---

src/views/assets/Asset/AssetCreateUpdate/DatabaseCreateUpdate.vue

fix: mongodb无指定数据库时，一些自动化任务会失败

fix: mongodb无指定数据库时，一些自动化任务会失败

---

src/components/Dialog/DiffDetail.vue
src/components/ResourceActivity/index.vue
src/router/audit/audits.js
src/views/audits/LoginLog/LoginLogDetail/Detail.vue
src/views/audits/LoginLog/LoginLogDetail/index.vue
src/views/audits/LoginLog/LoginLogList.vue
src/views/audits/OperateLog/OperateLogDetail/Detail.vue
src/views/audits/OperateLog/OperateLogList.vue

perf: 优化Activity日志[操作日志、登录日志]显示

perf: 优化Activity日志[操作日志、登录日志]显示

---

src/views/assets/Asset/AssetCreateUpdate/DatabaseCreateUpdate.vue

perf: 修改PostgreSQL数据库参数为必填

---

src/views/audits/OperateLog/OperateLogDetail/Detail.vue
src/views/audits/OperateLog/OperateLogList.vue

fix: 点击操作日志详情空白的问题

---

src/views/sessions/SessionDetail/index.vue

fix: 解决一些资源的Activity日志无法查看问题

---

src/views/assets/Asset/AssetList/components/BaseList.vue

fix: SSL资产克隆无SSL等选项

---

src/views/assets/Asset/AssetList/WebList.vue

fix: Web资产提示有误

---

src/components/FormFields/ProtocolSelector/ProtocolSettingDialog.vue
src/components/FormFields/ProtocolSelector/index.vue
src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json

feat: Windows类型资产增加winrm协议

---

src/components/FormFields/PhoneInput.vue
src/components/FormFields/index.js
src/views/profile/ProfileImprovement.vue
src/views/profile/ProfileUpdate/ProfileUpdate.vue
src/views/users/User/UserCreateUpdate.vue
src/views/users/User/UserDetail/UserInfo.vue

feat: 手机号码支持选择区号

---

src/components/FormFields/PhoneInput.vue
src/components/FormFields/index.js
src/views/profile/ProfileImprovement.vue
src/views/profile/ProfileUpdate/ProfileUpdate.vue
src/views/users/User/UserCreateUpdate.vue
src/views/users/User/UserDetail/UserInfo.vue

feat: 手机号支持选择区号

---

src/components/FormFields/PhoneInput.vue
src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/users/User/UserDetail/UserInfo.vue

fix: 优化手机号区号更新为空及展示问题

---

src/components/FormFields/PhoneInput.vue

fix: 解决更新手机号不同步的问题

---

src/components/FormFields/DynamicInput.vue
src/components/FormFields/index.js
src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Platform/AutomationParamsSetting.vue
src/views/assets/Platform/PlatformCreateUpdate.vue
src/views/assets/Platform/PlatformDetail/Automation.vue
src/views/assets/Platform/const.js

feat: 支持部分资源的自定义自动化任务(Ping/VerifyAccount/ChangeSecret)

feat: 支持部分资源的自定义自动化任务(Ping/VerifyAccount/ChangeSecret)

---

src/layout/components/NavHeader/SiteMessages.vue

perf: 优化站内信查看已读逻辑

---

src/components/FormFields/ProtocolSelector/index.vue

Revert "perf: 自定义平台协议名称宽度自适应显示"

---

src/components/FormFields/DatetimeRangePicker.vue
src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json

feat: 时间组件快捷支持->半年、1年选项

---

src/components/QuickActions/action.vue
src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/profile/ProfileInfo.vue

perf: 非本地用户无法解绑飞书、企业微信、钉钉

---

src/components/FormFields/PhoneInput.vue
src/views/users/User/UserDetail/UserInfo.vue
src/views/users/User/UserList.vue

fix: 去掉手机区号和手机号码之间的空格

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/utils/common.js
src/views/sessions/FTPLogList.vue
src/views/sessions/SessionList/OfflineList.vue

feat: 支持文件上传下载备份

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Cloud/Account/AccountCreateUpdate.vue
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/const.js

feat: 云同步支持UCloud公有云

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/tickets/AssignedTicketList.vue
src/views/tickets/BaseTicketList.vue
src/views/tickets/MyTicketList.vue

feat: 支持批量审批工单

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/tickets/AssignedTicketList.vue

perf: 优化批量审批翻译

---

src/views/assets/Cloud/Strategy/StrategyList.vue

fix: 云同步策略不支持导出

---

src/components/Form/FormFields/DynamicInput.vue

fix: 解决自动化动态列表组件添加内容会频闪退闪的问题

---

src/views/assets/Cloud/Strategy/components/ActionInput.vue
src/views/assets/Cloud/Strategy/components/RuleInput.vue

fix: 策略删除动作和规则时提示404

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/settings/Tool/Base.vue
src/views/settings/Tool/Nmap.vue
src/views/settings/Tool/Ping.vue
src/views/settings/Tool/Tcpdump.vue
src/views/settings/Tool/Telnet.vue

feat: telnet、ping支持批量测试，增加IP格式提示

feat: telnet、ping支持批量测试，增加IP格式提示

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/settings/Auth/CAS.vue

fix: cas登录失败，属性映射增加提醒

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/settings/Msg/SMS/SMSFileCustom.vue
src/views/settings/Msg/SMS/index.vue

feat: 支持自定义短信认证(文件)

---

src/views/assets/Cloud/SyncInstanceTask/components/SyncInstanceTaskStrategy/index.vue

fix: 新创建的云同步任务策略为空的问题

---

src/views/assets/Cloud/Account/AccountDetail/index.vue

fix: 云账号详情页面更新报错

---

src/views/assets/Cloud/SyncInstanceTask/components/SyncInstanceTaskStrategy/AttrDialog.vue

fix: 解决更新云同步任务时，优先级无法更新问题

---

src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskDetail/detail.vue

fix: 云同步任务详情界面删除无用的按钮

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/const.js

feat: 支持深信服云平台和阿里云专有云

---

src/views/users/User/UserList.vue

perf: 用户列表可展示更多api返回的字段信息

---

src/views/accounts/AccountGather/AccountGatherList.vue

Revert "perf: 账号收集翻译"

---

src/layout/components/Page/PageHeading.vue

perf: 资源详情页面标题长度超过一行则省略表示

---

src/views/settings/Feature/Ticket.vue

feat: 支持工单链接直接免密审批

---

src/components/Table/ListTable/index.vue

Revert "fix: 刷新页面根据搜索条件过滤出对应的资源"

---

src/components/Apps/AccountListTable/AccountList.vue
src/components/Apps/AssetSelect/dialog.vue
src/components/Table/DataTable/compenents/el-data-table/el-data-table.vue
src/layout/components/TabPage/index.vue
src/views/accounts/AccountChangeSecret/AccountChangeSecretDetail/AccountChangeSecretAsset/index.vue
src/views/accounts/AccountGather/AccountGatherTaskList.vue
src/views/accounts/AccountTemplate/AccountTemplateDetail/Account.vue
src/views/acl/CommandAcl/index.vue
src/views/assets/Asset/AssetDetail/PermUser.vue
src/views/assets/Asset/AssetList/components/BaseList.vue
src/views/assets/Asset/AssetList/index.vue
src/views/assets/Cloud/Account/AccountList.vue
src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskDetail/AssetList.vue
src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskDetail/HistoryList.vue
src/views/labels/LabelResourcesDialog.vue
src/views/ops/Job/AdhocOpenDialog.vue
src/views/sessions/SessionList/BaseList.vue
src/views/settings/Applet/Applet/AppletList.vue
src/views/settings/Applet/VirtualApp/VirtualAppList.vue
src/views/users/Group/UserGroupDetail/GroupUser.vue
src/views/users/User/UserDetail/index.vue

Revert "fix: 刷新页面搜索条件丢失的问题"

---

src/views/assets/Cloud/Account/AccountList.vue

feat: 云账号测试支持选择地域

---

yarn.lock

Revert "build(deps): bump follow-redirects from 1.15.3 to 1.15.4"

---

src/components/Form/FormFields/Select2.vue
src/views/assets/Cloud/Account/AccountList.vue

perf: 优化云同步测试账号再次打开后不显示上次选的地域信息

perf: 优化云同步测试账号再次打开后不显示上次选的地域信息

---

src/views/settings/Feature/index.vue

Revert "perf: remove ticket feature"

---

src/i18n/langs/en.json
src/i18n/langs/ja.json
src/i18n/langs/zh.json
src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskCreateUpdate.vue

perf: 云同步支持同步完成后自动删除云端已经释放的资产

---

src/components/Table/TagSearch/index.vue
src/views/tickets/BaseTicketList.vue

Revert "fix: By default, the pending approval list page filters out tickets that have not yet been approved"

---

src/components/Table/TagSearch/index.vue
src/views/tickets/BaseTicketList.vue

This reverts commit 91c44d05009f8659c1bb48650a278b6f72004d52.

Revert "fix: 待我审批列表页面默认过滤出还未审批的工单"

---

src/components/Apps/AssetTreeTable/index.vue

Revert "fixed: Fixed page refresh when tree nodes are clicked"

---

src/router/console/assets.js

Revert "perf: Platform global"

---

src/layout/components/GenericCreateUpdatePage/index.vue

Revert "perf: drawer el-radio-group css"

---

src/views/accounts/AccountPush/AccountPushList.vue

feat: Add batch activation and disable options in account push tasks

---

src/components/Tree/DataZTree/components/ZTree/index.vue

Revert "fix: A scroll bar appears in the asset tree on the left side of the adhoc."
